"""The noise generator itself: headless, no window. Launched by Envision as an
XR plugin, which starts it with the XR service and terminates it when the
service stops (see the .desktop file generated by install.sh).

`vr-noise-mask set` saves the config and sends SIGUSR1 to re-read it.
"""
import signal
import threading

from .config import clear_state, load_config, write_state
from .engine import NoiseEngine


def run():
    wake = threading.Event()
    stop = threading.Event()
    reload = threading.Event()

    def on_term(*_):
        stop.set()
        wake.set()

    def on_usr1(*_):
        reload.set()
        wake.set()

    for sig in (signal.SIGTERM, signal.SIGINT, signal.SIGHUP):
        signal.signal(sig, on_term)
    signal.signal(signal.SIGUSR1, on_usr1)

    # State file appears only once the handlers exist (a SIGUSR1 before that
    # would kill us), and before the config is read (so a `set` racing startup
    # either lands in this read or signals us).
    engine = NoiseEngine()
    write_state(False)

    def apply_config():
        cfg = load_config()
        engine.volume_pct = cfg["volume_pct"]
        engine.enabled = cfg["enabled"]
        if cfg["device_match"] != engine.device_match:
            engine.device_match = cfg["device_match"]
            engine.current_target = None  # force re-check/reopen
        engine.poke()

    try:
        apply_config()
        engine.start_ticker(on_change=lambda: write_state(engine.is_active))
        while True:
            wake.wait()
            wake.clear()
            if stop.is_set():
                break
            if reload.is_set():
                reload.clear()
                apply_config()
    finally:
        clear_state()
        engine.shutdown()
