"""The noise generator itself: headless, no window. Launched by Envision as an
XR plugin, which starts it with the XR service and terminates it when the
service stops (see the .desktop file generated by install.sh).

Config edits (from the plasmoid or `vr-noise-mask set`) are picked up live.
"""
import signal
import threading

from .config import CONFIG_PATH, clear_state, load_config, write_state
from .engine import NoiseEngine


def _config_mtime():
    try:
        return CONFIG_PATH.stat().st_mtime
    except OSError:
        return None


def run():
    stop = threading.Event()
    for sig in (signal.SIGTERM, signal.SIGINT, signal.SIGHUP):
        signal.signal(sig, lambda *_: stop.set())

    cfg = load_config()
    engine = NoiseEngine(volume_pct=cfg["volume_pct"], device_match=cfg["device_match"])
    engine.enabled = cfg["enabled"]
    engine.start_ticker()

    mtime = _config_mtime()
    try:
        while True:
            write_state(engine.is_active)
            if stop.wait(1.0):
                break
            new_mtime = _config_mtime()
            if new_mtime == mtime:
                continue
            mtime = new_mtime
            cfg = load_config()
            engine.volume_pct = cfg["volume_pct"]
            engine.enabled = cfg["enabled"]
            if cfg["device_match"] != engine.device_match:
                engine.device_match = cfg["device_match"]
                engine.current_target = None  # force re-check/reopen
    finally:
        clear_state()
        engine.shutdown()
